### ISSUE TITLE
Exception when uploading a file

### ISSUE THREAD

**Issue by dobos** [sciserver/graywulf#91]
[Jhu.Graywulf.IO.Tasks.TableCopyException]
Table copy failed: An item with the same key has already been added.
   at Jhu.Graywulf.IO.Tasks.CopyTableBase.HandleException(Exception ex, TableCopyResult result) in C:\Data\dobos\project\skyquery-all-v1.3\graywulf\dll\Jhu.Graywulf.IO\IO\Tasks\CopyTableBase.cs:line 432
   at Jhu.Graywulf.IO.Tasks.ImportTable.OnExecute() in C:\Data\dobos\project\skyquery-all-v1.3\graywulf\dll\Jhu.Graywulf.IO\IO\Tasks\ImportTable.cs:line 177
   at Jhu.Graywulf.Tasks.CancelableTask.Execute() in C:\Data\dobos\project\skyquery-all-v1.3\graywulf\dll\Jhu.Graywulf.RemoteService\Tasks\CancelableTask.cs:line 87
   at Jhu.Graywulf.RemoteService.RemoteServiceBase.Execute() in C:\Data\dobos\project\skyquery-all-v1.3\graywulf\dll\Jhu.Graywulf.RemoteService\RemoteService\RemoteServiceBase.cs:line 45
   at Jhu.Graywulf.Web.UI.Apps.MyDB.Import.ImportUploadedFile() in C:\Data\dobos\project\skyquery-all-v1.3\graywulf\web\Jhu.Graywulf.Web.UI\Apps\MyDB\Import.aspx.cs:line 154
   at Jhu.Graywulf.Web.UI.Apps.MyDB.Import.Ok_Click(Object sender, EventArgs e) in C:\Data\dobos\project\skyquery-all-v1.3\graywulf\web\Jhu.Graywulf.Web.UI\Apps\MyDB\Import.aspx.cs:line 97
   at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   at Jhu.Graywulf.Web.UI.PageBase.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) in C:\Data\dobos\project\skyquery-all-v1.3\graywulf\dll\Jhu.Graywulf.Web\Web\UI\PageBase.cs:line 182
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

[System.ArgumentException]
An item with the same key has already been added.
   at Jhu.Graywulf.Tasks.CancelableDbCommand.ExecuteReader(CommandBehavior behavior, Action`1 action) in C:\Data\dobos\project\skyquery-all-v1.3\graywulf\dll\Jhu.Graywulf.RemoteService\Tasks\CancelableDbCommand.cs:line 128
   at Jhu.Graywulf.IO.Tasks.CopyTableBase.CopyFromCommand(ISmartCommand cmd, DestinationTable destination, TableCopyResult result) in C:\Data\dobos\project\skyquery-all-v1.3\graywulf\dll\Jhu.Graywulf.IO\IO\Tasks\CopyTableBase.cs:line 273
   at Jhu.Graywulf.IO.Tasks.CopyTableBase.CopyFromFile(DataFileBase source, DestinationTable destination, TableCopyResult result) in C:\Data\dobos\project\skyquery-all-v1.3\graywulf\dll\Jhu.Graywulf.IO\IO\Tasks\CopyTableBase.cs:line 256
   at Jhu.Graywulf.IO.Tasks.ImportTable.OnExecute() in C:\Data\dobos\project\skyquery-all-v1.3\graywulf\dll\Jhu.Graywulf.IO\IO\Tasks\ImportTable.cs:line 173

**Comment by dobos** [comment]
This likely happens in the anonymous function at CopyTableBase.cs:279 and is related to repeating table columns but certainly before executing bulk copy.
